GHA Workflow added

diff --git a/.github/workflows/bankapp-cicd.yml b/.github/workflows/bankapp-cicd.yml
--- a/.github/workflows/bankapp-cicd.yml
+++ b/.github/workflows/bankapp-cicd.yml
@@ -13,7 +13,7 @@ on:
           - green
 
 jobs:
-  build-test-scan:
+  build-test-package:
     runs-on: ubuntu-latest
     env:
       IMAGE_NAME: sidraut007/spring-bankapp
@@ -22,8 +22,6 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-        with:
-          ref: main
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -42,10 +40,10 @@ jobs:
       - name: Maven compile
         run: mvn compile
 
-      - name: Maven test (skip tests?)
+      - name: Run tests
         run: mvn test -DskipTests=true
 
-      - name: Maven install (skip tests)
+      - name: Package application
         run: mvn clean install -DskipTests=true
 
   docker-build-push:
@@ -109,6 +107,8 @@ jobs:
 
             echo "Waiting for app to be healthy..."
             sleep 20
+            curl -f http://localhost:8080/actuator/health || (echo "Health check failed!" && exit 1)
+
 
 
   # update-k8s-manifest:
